### ISSUE TITLE
readme中说为什么使用SDB的疑惑？

### ISSUE THREAD

**Issue by luotian** [yemingfeng/sdb#1]
为什么需要 SDB？
试想以下业务场景：

计数服务：对内容的点赞、播放等数据进行统计
评论服务：发布评论后，查看某个内容的评论列表
推荐服务：每个用户有一个包含内容和权重推荐列表
以上几个业务场景，都可以通过 MySQL + Redis 的方式实现。

MySQL 在这个场景中充当了持久化的能力，Redis 提供了在线服务的读写能力。

能不能只使用一个存储就满足上面的场景呢？

答案是：非常少的。有些数据库要么是支持的数据结构不够丰富，要么数据结构不够丰富，要么是接入成本太高。。。。。。

为了解决上述问题，SDB 产生了。

=============================================================================

对于这个问题，直接使用redis就可以做到啊，又可以当内存数据库用，又可以持久化使用。

**Comment by yemingfeng** [comment]
嗯嗯。这个问题在上面已经回答了。
是因为 redis 的持久化会丢失数据的
